# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- script: dotnet pack --configuration $(buildConfiguration)
  displayName: 'dotnet pack $(buildConfiguration)'
- script: dotnet nuget update source "azure" -u $(PAT) -p $(PAT) --configfile ./nuget.config --store-password-in-clear-text
  displayName: 'dotnet nuget add source'
- script: dotnet nuget push --source "azure" --api-key az "./MojangApi/"
  displayName: 'dotnet nuget push'
